namespace YGOHandAnalysisFramework.Features.Comparison.Formatting;

public delegate IDataComparisonFormatter CreateDataComparisonFormatter(IEnumerable<IDataComparisonFormatterEntry> entries, IEnumerable<IDataComparisonCategoryResults> results);
