using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CardSourceGenerator
{
    [Generator]
    internal class SourceGenerator : ISourceGenerator
    {
        private const string YGOCards = nameof(YGOCards);
        private const string YGOCardName = nameof(YGOCardName);
        private const string YGOCard = nameof(YGOCard);

        private static string GetIdentifier(string name)
        {
            var identifier = new StringBuilder();
            identifier.Append("C_");

            foreach (var chr in name)
            {
                if (char.IsLetterOrDigit(chr))
                {
                    identifier.Append(chr);
                }
            }

            return identifier.ToString();
        }

        private static string GetName(string name)
        {
            var cardName = new StringBuilder();

            foreach (var chr in name)
            {
                if (chr == '"')
                {
                    cardName.Append('\\');
                    cardName.Append('"');
                }
                else if (chr == '\\')
                {
                    cardName.Append(@"\\");
                }
                else
                {
                    cardName.Append(chr);
                }
            }

            return cardName.ToString();
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var cards = new HashSet<INamedYGOCard>();
            var filesRead = new List<string>();
            foreach (var file in context.AdditionalFiles.Where(text => Path.GetExtension(text.Path).Equals(".json")))
            {
                if (file.GetText() is SourceText text)
                {
                    filesRead.Add(file.Path);
                    cards.UnionWith(YGOProData.GetCardData(text.ToString()));
                }
            }

            CreateRawNamesSourceCode(context, cards);
            CreateMappedNamesSourceCode(context, cards);
            CreatePathsSourceCode(context, filesRead);
            CreateCardDataCode(context);
        }

        private static void CreatePathsSourceCode(GeneratorExecutionContext context, IEnumerable<string> paths)
        {
            var sb = new StringBuilder();

            sb.Append($@"// <auto-generated/>
// {DateTime.UtcNow}
#nullable enable
using System.Text.Json;
using System.Collections.Generic;

namespace {nameof(CardSourceGenerator)}
{{
    public static partial class {YGOCards}
    {{
        public static IReadOnlyList<string> Paths {{ get; }} = new List<string>()
        {{");

            foreach (var p in paths)
            {
                sb.Append($@"
            @""{Path.GetFullPath(p)}"",");
            }

            sb.Append(@"
        };
    }
}");

            context.AddSource($"{YGOCards}.Paths.g.cs", sb.ToString());
        }

        private static void CreateMappedNamesSourceCode(GeneratorExecutionContext context, IReadOnlyCollection<INamedYGOCard> cards)
        {
            var sb = new StringBuilder();
            sb.Append($@"// <auto-generated/>
// {DateTime.UtcNow}
using System.Collections.Generic;

namespace {nameof(CardSourceGenerator)}
{{
    public static partial class {YGOCards}
    {{
        public static IReadOnlyDictionary<string, {YGOCards}.{YGOCardName}> CardNameMap {{ get; }} = new Dictionary<string, {YGOCards}.{YGOCardName}>
        {{");

            foreach (var card in cards)
            {
                sb.Append($@"
            {{ ""{GetName(card.Name)}"", new {YGOCards}.{YGOCardName}(""{GetName(card.Name)}"") }},");
            }

            sb.Append($@"
        }};

        public static IReadOnlySet<{YGOCards}.{YGOCardName}> AllCardNames {{ get; }}

        static {YGOCards}()
        {{
            AllCardNames = new HashSet<{YGOCards}.{YGOCardName}>(CardNameMap.Values);
        }}
    }}
}}");
            context.AddSource($"{YGOCards}.MappedNames.g.cs", sb.ToString());
        }

        private static void CreateRawNamesSourceCode(GeneratorExecutionContext context, IReadOnlyCollection<INamedYGOCard> cards)
        {
            var sb = new StringBuilder();
            sb.Append($@"// <auto-generated/>
// {DateTime.UtcNow}
using System;
using System.Diagnostics;

namespace {nameof(CardSourceGenerator)}
{{
    public static partial class {YGOCards}
    {{
        [DebuggerDisplay(""{{Name}}"")]
        public readonly struct {YGOCardName} : IEquatable<{YGOCardName}>, IComparable<{YGOCardName}>
        {{
            public string Name {{ get; }} = string.Empty;

            public {YGOCardName}(string name)
            {{
                Name = name;
            }}

            public bool Equals({YGOCardName} other) => Name.Equals(other.Name, StringComparison.Ordinal);
            public override bool Equals(object obj) => obj is {YGOCardName} other && Equals(other);
            public override int GetHashCode() => StringComparer.Ordinal.GetHashCode(Name);
            public static bool operator ==({YGOCardName} x, {YGOCardName} y) => x.Equals(y);
            public static bool operator !=({YGOCardName} x, {YGOCardName} y) => !(x == y);

            public int CompareTo({YGOCardName} other) => StringComparer.Ordinal.Compare(Name, other.Name);
            public static bool operator >({YGOCardName} x, {YGOCardName} y) => x.CompareTo(y) > 0;
            public static bool operator <({YGOCardName} x, {YGOCardName} y) => x.CompareTo(y) < 0;
            public static bool operator >=({YGOCardName} x, {YGOCardName} y) => x.CompareTo(y) >= 0;
            public static bool operator <=({YGOCardName} x, {YGOCardName} y) => x.CompareTo(y) <= 0;
        }}");

            foreach (var card in cards)
            {
                var identifier = GetIdentifier(card.Name);
                var name = GetName(card.Name);

                sb.Append($@"
        public static {YGOCardName} {identifier} {{ get; }} = new {YGOCardName}(""{name}"");");
            }

            sb.Append(@"
    }
}");
            context.AddSource($"{YGOCards}.Names.g.cs", sb.ToString());
        }

        private static void CreateCardDataCode(GeneratorExecutionContext context)
        {
            var sb = new StringBuilder();

            sb.Append($@"// <auto-generated/>
// {DateTime.UtcNow}
#nullable enable
using System;
using System.IO;
using System.Text.Json;
using System.Collections.Generic;

namespace {nameof(CardSourceGenerator)}
{{
    public static partial class {YGOCards}
    {{
        public interface IYGOCard : IYGOCard<{YGOCards}.{YGOCardName}> {{ }}

        private sealed class YGOProCard : IYGOCard
        {{
            public {YGOCards}.{YGOCardName} Name {{ get; }}
            public StartingDeckLocation StartingLocation {{ get; }}
            public int? Level {{ get; }}
            public int? AttackPoints {{ get; }}
            public int? DefensePoints {{ get; }}
            public string? MonsterType {{ get; }}
            public string? MonsterAttribute {{ get; }}

            public YGOProCard(JsonElement element)
            {{
                {{
                    if (!element.TryGetProperty(""name"", out var el))
                    {{
                        throw new Exception(""name not found"");
                    }}

                    var name = el.GetString() ?? throw new Exception(""name not a string"");

                    if(!{YGOCards}.CardNameMap.TryGetValue(name, out var cardName))
                    {{
                        throw new Exception(""{YGOCardName} not found"");
                    }}

                    Name = cardName;
                }}

                {{
                    if (!element.TryGetProperty(""type"", out var el))
                    {{
                        throw new Exception(""type not found"");
                    }}

                    var cardType = el.GetString() ?? throw new Exception(""type not a string"");
                    StartingLocation = DetermineStartingLocation(cardType);
                }}

                {{
                    if (element.TryGetProperty(""level"", out var el))
                    {{
                        Level = GetAtkOrDef(el);
                    }}
                }}

                {{
                    if (element.TryGetProperty(""atk"", out var el))
                    {{
                        AttackPoints = GetAtkOrDef(el);
                    }}
                }}

                {{
                    if (element.TryGetProperty(""def"", out var el))
                    {{
                        DefensePoints = GetAtkOrDef(el);
                    }}

                }}

                {{
                    if (element.TryGetProperty(""race"", out var el))
                    {{
                        MonsterType = el.GetString() ?? throw new Exception(""type not a string"");
                    }}
                }}

                {{
                    if (element.TryGetProperty(""attribute"", out var el))
                    {{
                        MonsterAttribute = el.GetString() ?? throw new Exception(""attribute not a string"");
                    }}
                }}
            }}

            private static int? GetAtkOrDef(JsonElement element)
            {{
                return element.ValueKind switch
                {{
                    JsonValueKind.Null => null,
                    JsonValueKind.Number => element.GetInt32(),
                    _ => throw new InvalidOperationException(element.GetRawText())
                }};
            }}
        }}

        private sealed class YGOProData
        {{
            public IReadOnlyList<IYGOCard> Data {{ get; }} = Array.Empty<IYGOCard>();

            public YGOProData(JsonElement element)
            {{
                var list = new List<IYGOCard>();
                Data = list;

                if (!element.TryGetProperty(""data"", out var el))
                {{
                    throw new Exception(""data not found"");
                }}

                foreach (var obj in el.EnumerateArray())
                {{
                    list.Add(new YGOProCard(obj));
                }}
            }}
        }}

        private static StartingDeckLocation DetermineStartingLocation(string location)
        {{
            var span = location.AsSpan();
            var fusion = ""fusion"".AsSpan();
            var synchro = ""synchro"".AsSpan();
            var xyz = ""xyz"".AsSpan();
            var link = ""link"".AsSpan();

            if (span.Contains(fusion, StringComparison.OrdinalIgnoreCase))
            {{
                return StartingDeckLocation.ExtraDeck;
            }}

            if (span.Contains(synchro, StringComparison.OrdinalIgnoreCase))
            {{
                return StartingDeckLocation.ExtraDeck;
            }}

            if (span.Contains(xyz, StringComparison.OrdinalIgnoreCase))
            {{
                return StartingDeckLocation.ExtraDeck;
            }}

            if (span.Contains(link, StringComparison.OrdinalIgnoreCase))
            {{
                return StartingDeckLocation.ExtraDeck;
            }}

            return StartingDeckLocation.MainDeck;
        }}

        public static IReadOnlyList<IYGOCard> LoadCardDataFromYgoPro(string path)
        {{
            using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
            using var document = JsonDocument.Parse(stream);
            return new YGOProData(document.RootElement).Data;
        }}

        public static IReadOnlyDictionary<{YGOCards}.{YGOCardName}, IYGOCard> LoadAllCardDataFromYgoPro()
        {{
            var cardData = new Dictionary<{YGOCards}.{YGOCardName}, IYGOCard>();

            foreach (var path in {YGOCards}.Paths)
            {{
                var list = LoadCardDataFromYgoPro(path);

                foreach (var card in list)
                {{
                    cardData[card.Name] = card;
                }}
            }}

            return cardData;
        }}
    }}
}}");

            context.AddSource($"{YGOCards}.CardData.g.cs", sb.ToString());
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}
